import Head from "next/head";
import { Inter } from "@next/font/google";
import { Button } from "antd";
import { Banner } from "./homeStyles";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Umbartha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header home={true} />
      <Banner></Banner>
    </>
  );
}
